/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.crmshopping.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-16-2009
 * 
 * XDoclet definition:
 * @struts.form name="customerForm"
 */
public class CustomerForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** password property */
	
	/** customerId property */
	private String customerId;
	private String name;
	private String Password;	
	private String dob;
	private String gender;
	private String contact;
	private String address;
	private String email;
	

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return Password;
	}

	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.Password = password;
	}

	/** 
	 * Returns the customerId.
	 * @return String
	 */
	public String getCustomerId() {
		return customerId;
	}

	/** 
	 * Set the customerId.
	 * @param customerId The customerId to set
	 */
	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContact() {
		return contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getDob() {
		return dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}