/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.crmshopping.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-15-2009
 * 
 * XDoclet definition:
 * @struts.form name="categoryForm"
 */
public class CategoryForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** superCategoryId property */
	private String superCategoryId;

	/** categoryName property */
	private String categoryName;

	/** categoryId property */
	private String categoryId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the superCategoryId.
	 * @return String
	 */
	public String getSuperCategoryId() {
		return superCategoryId;
	}

	/** 
	 * Set the superCategoryId.
	 * @param superCategoryId The superCategoryId to set
	 */
	public void setSuperCategoryId(String superCategoryId) {
		this.superCategoryId = superCategoryId;
	}

	/** 
	 * Returns the categoryName.
	 * @return String
	 */
	public String getCategoryName() {
		return categoryName;
	}

	/** 
	 * Set the categoryName.
	 * @param categoryName The categoryName to set
	 */
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	/** 
	 * Returns the categoryId.
	 * @return String
	 */
	public String getCategoryId() {
		return categoryId;
	}

	/** 
	 * Set the categoryId.
	 * @param categoryId The categoryId to set
	 */
	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}
}