/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.crmshopping.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-19-2009
 * 
 * XDoclet definition:
 * @struts.form name="productForm"
 */
public class ProductForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	/** categoryId property */
	private String subCategory;
	
	public String getSubCategory() {
		return subCategory;
	}
	public void setSubCategory(String subCategory) {
		this.subCategory = subCategory;
	}

	
}