CREATE TABLE CUSTOMER
(
 CUSTOMERID VARCHAR2(20),
 PASSWORD VARCHAR2(50),
 NAME VARCHAR2(100),
 DOB DATE,
 GENDER VARCHAR2(10),
 CONTACT VARCHAR2(20),
 ADDRESS VARCHAR2(100),
 EMAIL VARCHAR2(20),
 CONSTRAINT PK_CUSTOMERID PRIMARY KEY(CUSTOMERID)
 );

CREATE TABLE AGENT
(

 AGENTID VARCHAR2(20),
 PASSWORD VARCHAR2(50),
 NAME VARCHAR2(100),
 DOB DATE,
 GENDER VARCHAR2(10),
 CONTACT VARCHAR2(20),
 ADDRESS VARCHAR2(100),
 EMAIL VARCHAR2(20),
 CONSTRAINT PK_AGENTID PRIMARY KEY(AGENTID)
 );

CREATE TABLE CATEGORY
(
CATEGORYID VARCHAR2(20),
CATEGORYNAME VARCHAR2(20),
SUPERCATEGORYID VARCHAR2(20),
CONSTRAINT PK_CATEGORYID PRIMARY KEY(CATEGORYID),
CONSTRAINT FK_SUPERCATEGORYID FOREIGN KEY(SUPERCATEGORYID) REFERENCES CATEGORY(CATEGORYID)
);

CREATE TABLE SCHEME
(
	SCHEMEID VARCHAR2(20),
	SCHEMEVALIDITY VARCHAR2(20),
	SCHEMENAME VARCHAR2(100),
	SCHEMEDETAILS VARCHAR2(200), 
	CONSTRAINT PK_SCHEMEID PRIMARY KEY(SCHEMEID)
);

CREATE TABLE PRODUCT
(
	PRODUCTID VARCHAR2(20),
	SCHEMEID VARCHAR2(20),
	CATEGORYID VARCHAR2(20),
	NAME VARCHAR2(100),
	DESCRIPTION VARCHAR2(500),
	COST NUMBER(8,2),
	CONSTRAINT PK_PRODUCTID PRIMARY KEY(PRODUCTID),
	CONSTRAINT FK_CATEGORYID FOREIGN KEY(CATEGORYID) REFERENCES CATEGORY(CATEGORYID),
	CONSTRAINT FK_SCHEMEID FOREIGN KEY(SCHEMEID) REFERENCES SCHEME(SCHEMEID)
);

CREATE TABLE ORDERS
(
	ORDERID VARCHAR2(20),
	CUSTOMERID VARCHAR2(20),
	PRODUCTID VARCHAR2(20),
	QUANTITY NUMBER(3),
	DATEOFORDER DATE,
	CONSTRAINT PK_ORDERID PRIMARY KEY(ORDERID),	
	CONSTRAINT FK_ORDER_CUST FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID),
	CONSTRAINT FK_PRODUCTID FOREIGN KEY(PRODUCTID) REFERENCES PRODUCT(PRODUCTID)

);

CREATE TABLE AGENTPRODUCT 
(
	AGENTID VARCHAR2(20),
	PRODUCTID VARCHAR2(20),
	FAMILIARITYLEVEL VARCHAR2(20),
	CONSTRAINT FK_AGENTPROD_AGENT FOREIGN KEY(AGENTID) REFERENCES AGENT(AGENTID),
	CONSTRAINT FK_AGENTPROD_PROD FOREIGN KEY(PRODUCTID) REFERENCES PRODUCT(PRODUCTID),
	CONSTRAINT PK_AGENTPROD PRIMARY KEY(AGENTID,PRODUCTID)
);

CREATE TABLE PAYMENTMODE
(
	PAYMENTMODEID VARCHAR2(20),
	PAYMENTMODETYPE VARCHAR2(20),
	CONSTRAINT PK_PAYMENTMODEID PRIMARY KEY(PAYMENTMODEID)
);

CREATE TABLE PAYMENT
(

	PAYMENTID VARCHAR2(20),
	CUSTOMERID VARCHAR2(20),
	SCHEMEID VARCHAR2(20),
	DATEOFPAYMENT DATE,
	AMOUNT VARCHAR2(20),
	CONSTRAINT PK_PAYMENTID PRIMARY KEY(PAYMENTID),
	CONSTRAINT FK_PAYMNT_CUST FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID),
	CONSTRAINT FK_PAYMT_SCHEME FOREIGN KEY(SCHEMEID) REFERENCES SCHEME(SCHEMEID)

);

CREATE SEQUENCE LANGUAGEID_SEQ START WITH 1001 INCREMENT BY 1;

CREATE TABLE LANGUAGE
(

	LANGUAGEID VARCHAR2(20),
	LANGUAGENAME VARCHAR2(20),
	CONSTRAINT PK_LANGUAGEID PRIMARY KEY(LANGUAGEID)

);

CREATE TABLE CUSTOMERLANGUAGE
(
	CUSTOMERID VARCHAR2(20),
	LANGUAGEID VARCHAR2(20),
	CUSTOMERLANGUAGE VARCHAR2(20),
	PREFERENCELEVEL VARCHAR2(20),
	CONSTRAINT FK_CUSTOMERID FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID),
	CONSTRAINT FK_LANGUAGEID FOREIGN KEY(LANGUAGEID) REFERENCES LANGUAGE(LANGUAGEID),
	CONSTRAINT PK_CUSTOMERLANGUAGE PRIMARY KEY(CUSTOMERID,LANGUAGEID)
	

);

CREATE TABLE AGENTLANGUAGE
(
	AGENTID VARCHAR2(20),
	LANGUAGEID VARCHAR2(20),
	AGENTLANGUAGE VARCHAR2(20),
	CONSTRAINT FK_AGENTID FOREIGN KEY(AGENTID) REFERENCES AGENT(AGENTID),
	CONSTRAINT FK_LANGUAGEID2 FOREIGN KEY(LANGUAGEID) REFERENCES LANGUAGE(LANGUAGEID),
	CONSTRAINT PK_AGENTLANGUAGE PRIMARY KEY(AGENTID,LANGUAGEID)

);