/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.crmshopping.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.crmshopping.businessbean.CategoryBean;
import com.crmshopping.dto.Category;
import com.crmshopping.struts.form.CategoryForm;
import com.crmshopping.util.DataAccessException;

/**
 * MyEclipse Struts Creation date: 03-15-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/category" name="categoryForm" parameter="action"
 *                scope="request"
 */
public class CategoryAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward getCategories(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		System.out.println("in Category action");
		CategoryForm categoryForm = (CategoryForm) form;
		
		String superCategoryId = categoryForm.getSuperCategoryId();
		System.out.println("SuperCategoryId is "+superCategoryId);
		CategoryBean categoryBean = new CategoryBean();
		ArrayList<Category> categories = null;

		try {
			categories = categoryBean.getCategories(superCategoryId);
		} catch (DataAccessException e) {
			e.printStackTrace();
		}
		
		HttpSession session = request.getSession();
		if(superCategoryId == null){
			session.setAttribute("categories", categories);
		}else{
			session.setAttribute("subCategories", categories);
		}
		session.setAttribute("selectedCategory", superCategoryId);		
		return mapping.findForward("welcome");
	}
}