/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.crmshopping.struts.action;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.crmshopping.businessbean.CategoryBean;
import com.crmshopping.businessbean.CustomerBean;
import com.crmshopping.dto.Category;
import com.crmshopping.dto.Customer;
import com.crmshopping.struts.form.CustomerForm;
import com.crmshopping.util.DataAccessException;

/** 
 * MyEclipse Struts
 * Creation date: 03-16-2009
 * 
 * XDoclet definition:
 * @struts.action path="/customer" name="customerForm" parameter="action" scope="request"
 */
public class CustomerAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward isValidUser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CustomerForm customerForm = (CustomerForm) form;// TODO Auto-generated method stub
		
		String CustomerId = customerForm.getCustomerId();
		String Password=customerForm.getPassword();
		
		System.out.println("CustomerId is "+CustomerId);
		System.out.println("Password is "+Password);
		
		CustomerBean customerBean = new CustomerBean();
		ArrayList<Category> categories = null;
		
		boolean status = false;

		try {
			status = customerBean.isValidUser(CustomerId,Password);
			
			
			System.out.println(status);
		} catch (DataAccessException e) {
			e.printStackTrace();
		}
		
		if(!status){
			return mapping.findForward("index");
		}else{
			
			CategoryBean categoryBean = new CategoryBean();
			try {
				categories = categoryBean.getCategories(null);
			} catch (DataAccessException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			HttpSession session = request.getSession();
			session.setAttribute("categories", categories);
			session.setAttribute("customerId", CustomerId);
			return mapping.findForward("welcome");
		}
	}
	public ActionForward addCustomer(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws DataAccessException {
		CustomerForm customerForm = (CustomerForm) form;// TODO Auto-generated method stub
		
		String CustomerId = customerForm.getCustomerId();
		String Password=customerForm.getPassword();
		String name=customerForm.getName();
		String dob=customerForm.getDob();
		System.out.println("-------In Action, User has entered dob as" + dob);
		SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
		java.util.Date utilDate=null;
		try {
			utilDate = sdf.parse(dob);
		} catch (ParseException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		String gender=customerForm.getGender();
		String contact=customerForm.getContact();
		String address=customerForm.getAddress();
		String email=customerForm.getEmail();
		
		Customer customer = new Customer();
		customer.setCustomerId(CustomerId);
		customer.setPassword(Password);
		customer.setName(name);
		customer.setDob(utilDate);
		customer.setGender(gender);
		customer.setContact(contact);
		customer.setAddress(address);
		customer.setEmail(email);
		System.out.println("CustomerId is "+CustomerId);
		System.out.println("Password is "+Password);
		
		CustomerBean customerBean = new CustomerBean();
		ArrayList<Category> categories = null;
		
		boolean status = false;

		status = customerBean.addCustomer(customer);
		
		
		System.out.println(status);
		
		if(status){
			request.setAttribute("message", "Registration is Successful and id is "+ CustomerId);
			return mapping.findForward("index");
			
		}else{
			
			
			return mapping.findForward("registration");
		}
	}
}